name: Golang Pipeline

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'

env:
  GOLANG_VERSION: "1.22"
  TERN_VERSION: "2.1.1"
  GOTESTSUM_VERSION: "1.10.1"
  IMAGE: ghcr.io/arthureichelberger/goboiler

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      psql:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run lint
        run: task lint
      - name: Run test
        run: task test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4.1.0
        if: success() || failure()
        with:
          report_paths: './unit-tests.xml'

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 8
    needs: [ ci ]
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: ./deploy.sh ${{ env.IMAGE }} -f Dockerfile --build-arg GOLANG_VERSION=${{ env.GOLANG_VERSION }} .
